export const booksBase = [
    {
        title: 'Atlas Shrugged',
        author: 'Ayn Rand',
        publisher: 'New American Library',
        category: ['Classics', 'Literary', 'Political'],
        description:
            "Who is John Galt? When he says that he will stop the motor of the world, is he a destroyer or a liberator? Why does he have to fight his battles not against his enemies but against those who need him most? Why does he fight his hardest battle against the woman he loves? You will know the answer to these questions when you discover the reason behind the baffling events that play havoc with the lives of the amazing men and women in this book. You will discover why a productive genius becomes a worthless playboy...why a great steel industrialist is working for his own destruction...why a composer gives up his career on the night of his triumph...why a beautiful woman who runs a transcontinental railroad falls in love with the man she has sworn to kill. Atlas Shrugged, a modern classic and Rand's most extensive statement of Objectivism--her groundbreaking philosophy--offers the reader the spectacle of human greatness, depicted with all the poetry and power of one of the twentieth century's leading artists.",
        pages: 1200,
        publishDate: 2005,
        price: 50,
        language: 'English',
        coverType: 'Hardcover',
        img: './assets/Atlas_Shrugged.jpg',
        id: 1,
    },
    {
        title: '1984',
        author: 'George Orwell',
        publisher: 'General Press',
        category: ['Classics', 'Psychological', 'Science Fiction'],
        description: 'none',
        pages: 246,
        publishDate: 2005,
        price: 30,
        language: 'English',
        coverType: 'Hardcover',
        img: './assets/1984.jpg',
        id: 2,
    },
    {
        title: 'Fahrenheit 451',
        author: 'Ray D. Bradbury',
        publisher: 'Simon & Schuster',
        category: ['Classics', 'Science Fiction', 'Media Tie-In'],
        description: 'none',
        pages: 256,
        publishDate: 2012,
        price: 16,
        language: 'English',
        coverType: 'Paperback',
        img: './assets/Fahrenheit_451.jpg',
        id: 3,
    },
    {
        title: 'Steppenwolf',
        author: 'Hermann Hesse',
        publisher: 'Picador USA',
        category: ['Classics', 'Literary'],
        description: 'none',
        pages: 224,
        publishDate: 2002,
        price: 17,
        language: 'German',
        coverType: 'Paperback',
        img: './assets/Steppenwolf.jpg',
        id: 4,
    },
    {
        title: 'The Twelve Chairs',
        author: 'Ilya Ilf, Evgeny Petrov',
        publisher: 'Northwestern University Press',
        category: ['Action & Adventure', 'Classics'],
        description: 'none',
        pages: 546,
        publishDate: 2011,
        price: 21,
        language: 'Russian',
        coverType: 'Paperback',
        img: './assets/The_Twelve_Chairs.jpg',
        id: 5,
    },
    {
        title: 'City',
        author: 'Clifford D. Simak',
        publisher: 'Open Road Media Science & Fantasy',
        category: ['Literary', 'Apocalyptic & Post-Apocalyptic', 'Genetic Engineering'],
        description: 'none',
        pages: 264,
        publishDate: 2015,
        price: 21,
        language: 'English',
        coverType: 'Paperback',
        img: './assets/City.jpg',
        id: 6,
    },
    {
        title: 'The Sane Society',
        author: 'Erich Fromm',
        publisher: 'Holt McDougal',
        category: ['Political Ideologies - Radicalism', 'Movements - Humanistic'],
        description: 'none',
        pages: 384,
        publishDate: 1990,
        price: 23,
        language: 'English',
        coverType: 'Paperback',
        img: './assets/The_Sane_Society.jpg',
        id: 7,
    },
    {
        title: 'The Three-Body Problem',
        author: 'Cixin Liu',
        publisher: 'Tor Books',
        category: ['Science Fiction - Hard Science Fiction', 'Science Fiction - Alien Contact'],
        description: 'none',
        pages: 416,
        publishDate: 2016,
        price: 17,
        language: 'English',
        coverType: 'Paperback',
        img: './assets/The_Three-Body_Problem.jpg',
        id: 8,
    },
    {
        title: "Cat's Cradle",
        author: 'Jr. Kurt Vonnegut',
        publisher: 'Perfection Learning',
        category: ['Classics'],
        description: 'none',
        pages: 287,
        publishDate: 1998,
        price: 29,
        language: 'English',
        coverType: 'Prebound',
        img: './assets/Cats_cradle.jpg',
        id: 9,
    },
    {
        title: 'Astrophysics for People in a Hurry',
        author: 'Neil Degrasse Tyson',
        publisher: 'W. W. Norton & Company',
        category: ['Physics - Astrophysics', 'Space Science'],
        description: 'none',
        pages: 224,
        publishDate: 2017,
        price: 18,
        language: 'English',
        coverType: 'Hardcover',
        img: './assets/Astrophysics_for_People_in_a_Hurry.jpg',
        id: 10,
    },
    {
        title: 'Altered Carbon',
        author: 'Richard K. Morgan',
        publisher: 'Del Rey Books',
        category: ['Science Fiction - Hard Science Fiction', 'Mystery & Detective - General'],
        description: 'none',
        pages: 400,
        publishDate: 2003,
        price: 16,
        language: 'English',
        coverType: 'Paperback',
        img: './assets/Altered_Carbon.jpg',
        id: 11,
    },
    {
        title: 'Sapiens. de Animales a Dioses',
        author: 'Yuval Noah Harari',
        publisher: 'Debate',
        category: ['Civilization', 'World - General', 'Life Sciences - Evolution'],
        description: 'none',
        pages: 496,
        publishDate: 2016,
        price: 16,
        language: 'Spanish',
        coverType: 'Paperback',
        img: './assets/Sapiens.jpg',
        id: 12,
    },
    {
        title: 'Secondhand Time: The Last of the Soviets',
        author: 'Svetlana Alexievich',
        publisher: 'Random House Trade',
        category: ['Social History'],
        description: 'none',
        pages: 496,
        publishDate: 2017,
        price: 19,
        language: 'English',
        coverType: 'Paperback',
        img: './assets/Secondhand_Time.jpg',
        id: 13,
    },
    {
        title: "Alindarka's Children: Things Will Be Bad",
        author: 'Alhierd Bacharevic',
        publisher: 'New Directions Publishing Corporation',
        category: ['Literary', 'Political'],
        description: 'none',
        pages: 352,
        publishDate: 2022,
        price: 19,
        language: 'English',
        coverType: 'Paperback',
        img: './assets/Alindarkas_Children.jpg',
        id: 14,
    },
    {
        title: 'Martin Iden',
        author: 'Jack London',
        publisher: 'Createspace Independent Publishing Platform',
        category: ['Classics'],
        description: 'none',
        pages: 234,
        publishDate: 2018,
        price: 15,
        language: 'Russian',
        coverType: 'Paperback',
        img: './assets/Martin_Iden.jpg',
        id: 15,
    },
    {
        title: "Howl's Moving Castle",
        author: 'Diana Wynne Jones',
        publisher: 'Greenwillow Books',
        category: ['Action & Adventure - General', 'Humorous Stories', 'Fantasy & Magic'],
        description: 'none',
        pages: 448,
        publishDate: 2008,
        price: 15,
        language: 'English',
        coverType: 'Paperback',
        img: './assets/Howls_Moving_Castle.jpg',
        id: 16,
    },
];
